services:
  wasm:
    build:
      context: .
      dockerfile: BaseProject.Web/Dockerfile
    ports:
      - "4000:80"
      - "4001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=443